# Generated by Django 4.1.1 on 2022-09-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='list_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
