# Generated by Django 4.1.1 on 2022-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movie_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
