# Generated by Django 4.1.1 on 2022-09-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_remove_movie_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating_user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating_web',
        ),
        migrations.AddField(
            model_name='movie',
            name='launch_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
