# Generated by Django 4.1.1 on 2022-09-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_remove_movie_rating_user_remove_movie_rating_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='launch_date',
        ),
    ]
