# Generated by Django 4.1.1 on 2022-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0007_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=70),
        ),
    ]
